#! /bin/sh 
#
CUP=./lib/java-cup-11a-runtime.jar
TMPL=./lib/stringtemplate-3.2.1.jar
ANTLR=./lib/antlr-2.7.7.jar
CLI=./lib/commons-cli-1.2.jar

CLASSPATH=.:${CUP}:${TMPL}:${ANTLR}:${CLI}
#
java -cp $CLASSPATH Cool $* > out.ll
if [ "$?" -eq "0" ]; then
    llvm-as out.ll -o out.bc -f
    if [ "$?" -eq "0" ]; then
        llc -O3 out.bc -o out.S -f       
        if [ "$?" -eq "0" ]; then
            gcc out.S -O3 -lgc -o out
        fi
    fi
fi
