
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 06 18:49:18 PST 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Nodes {
  /* terminals */
  public static final int METHOD = 1024;
  public static final int ATTRIBUTE = 1025;
}

