#! /bin/sh 
#
CUP=./lib/java-cup-11a-runtime.jar
TMPL=./lib/stringtemplate-3.2.1.jar
ANTLR=./lib/antlr-2.7.7.jar
CLI=./lib/commons-cli-1.2.jar

CLASSPATH=.:${CUP}:${TMPL}:${ANTLR}:${CLI}
#
java -cp $CLASSPATH ScanDriver $*