
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 07 13:55:22 PST 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INHERITS = 23;
  public static final int STRINGLIT = 41;
  public static final int CASE = 33;
  public static final int LPAREN = 10;
  public static final int SEMI = 4;
  public static final int MINUS = 16;
  public static final int RPAREN = 11;
  public static final int NOT = 20;
  public static final int TYPEID = 43;
  public static final int INTLIT = 40;
  public static final int LT = 18;
  public static final int IN = 32;
  public static final int COMMA = 7;
  public static final int CLASS = 22;
  public static final int FI = 27;
  public static final int DIV = 14;
  public static final int PLUS = 15;
  public static final int ASSIGN = 6;
  public static final int IF = 24;
  public static final int ID = 42;
  public static final int DOT = 8;
  public static final int OF = 34;
  public static final int EOF = 0;
  public static final int OD = 30;
  public static final int TRUE = 38;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int ISVOID = 37;
  public static final int EQ = 19;
  public static final int TIMES = 13;
  public static final int COLON = 5;
  public static final int NEG = 12;
  public static final int LBRACE = 2;
  public static final int ELSE = 26;
  public static final int WHILE = 28;
  public static final int ESAC = 35;
  public static final int LET = 31;
  public static final int THEN = 25;
  public static final int RBRACE = 3;
  public static final int LEQ = 17;
  public static final int RIGHTARROW = 21;
  public static final int AT = 9;
  public static final int FALSE = 39;
  public static final int DO = 29;
}

